/**
 * {{PROJECT_NAME}} - FPGA Top Module
 * Generated by Affogato
 *
 * This template provides:
 *   - 48MHz internal oscillator
 *   - SPI slave for ESP32 communication
 *   - RGB LED status indicator
 */
module top (
    // SPI interface to ESP32
    input wire FSPI_CLK,
    input wire FSPI_MOSI,
    output wire FSPI_MISO,
    input wire FSPI_CS,

    // RGB LED (directly accent accent to pins for simplicity)
    output wire RGB0,
    output wire RGB1,
    output wire RGB2
);

    // ==========================================================================
    // Internal 48MHz Oscillator
    // ==========================================================================
    wire clk_48mhz;

    SB_HFOSC #(
        .CLKHF_DIV("0b00")  // 48 MHz
    ) hfosc_inst (
        .CLKHFPU(1'b1),
        .CLKHFEN(1'b1),
        .CLKHF(clk_48mhz)
    );

    // Global clock buffer
    wire clk;
    SB_GB clk_gb (
        .USER_SIGNAL_TO_GLOBAL_BUFFER(clk_48mhz),
        .GLOBAL_BUFFER_OUTPUT(clk)
    );

    // ==========================================================================
    // Status Registers (exposed via SPI)
    // ==========================================================================
    // Example: 10-byte status packet
    // Byte 0: 0x00 (padding)
    // Byte 1: status flags
    // Bytes 2-5: counter value (big-endian)
    // Bytes 6-9: reserved

    reg [7:0] status_flags;
    reg [31:0] counter;

    wire [79:0] spi_data = {
        8'h00,              // Padding byte
        status_flags,       // Status flags
        counter,            // 32-bit counter
        32'h00000000        // Reserved
    };

    // ==========================================================================
    // SPI Slave (bulk status read)
    // ==========================================================================
    spi_slave_bulk #(
        .DATA_WIDTH(80)
    ) spi_inst (
        .i_cs(FSPI_CS),
        .i_sck(FSPI_CLK),
        .o_miso(FSPI_MISO),
        .i_data(spi_data)
    );

    // ==========================================================================
    // Heartbeat Counter
    // ==========================================================================
    always @(posedge clk) begin
        counter <= counter + 1;
    end

    // Status: set bit 0 when counter MSB is high
    always @(posedge clk) begin
        status_flags[0] <= counter[31];
        status_flags[7:1] <= 7'h00;
    end

    // ==========================================================================
    // RGB LED Driver
    // ==========================================================================
    // Blink pattern: Red=counter[24], Green=counter[25], Blue=counter[26]
    // This creates a ~3Hz cycling color pattern at 48MHz

    SB_RGBA_DRV #(
        .CURRENT_MODE("0b0"),       // Half current mode
        .RGB0_CURRENT("0b000001"),  // 4mA
        .RGB1_CURRENT("0b000001"),
        .RGB2_CURRENT("0b000001")
    ) rgb_driver (
        .CURREN(1'b1),
        .RGBLEDEN(1'b1),
        .RGB0PWM(counter[24]),
        .RGB1PWM(counter[25]),
        .RGB2PWM(counter[26]),
        .RGB0(RGB0),
        .RGB1(RGB1),
        .RGB2(RGB2)
    );

endmodule
